services:
  app-api-sbb:
    build: .
    container_name: api-database-sbb
    ports:
      - "5010:5000"
    env_file:
      - ./.env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped